### ISSUE TITLE
[UI & Feature] ChallengeScreen 에서 타이틀 Padding 조정 및 아래 테스크 배경 안이쁨

### ISSUE THREAD

**Issue by Damagucci-Juice** [MC2-LESSERAFIM/MC2-LESSERAFIM#33]
## 문제 상황 데모
![image](https://github.com/MC2-LESSERAFIM/MC2-LESSERAFIM/assets/50472122/b176068f-3408-41a9-9416-1e116d4f38c4)

**Comment by sohnseoyeon** [comment]
최근 pr 날린 **<[MERGE] 디자인(색상 및 폰트 사이즈 등) 수정 머지 2>** 의 **<[ADD] List 배경 수정>** 커밋에서 수정사항 확인하실 수 있습니다.

![Simulator Screenshot - iPhone 14 - 2023-05-14 at 14 51 56](https://github.com/MC2-LESSERAFIM/MC2-LESSERAFIM/assets/63771212/dbe986f6-abe8-4e73-b371-e802b2c412a9)
