### ISSUE TITLE
[REFACTOR] Naming 변경 사항 요청

### ISSUE THREAD

**Issue by Damagucci-Juice** [MC2-LESSERAFIM/MC2-LESSERAFIM#57]
# 요구사항
현행 네이밍이 햇갈림

| 비고 | 그림 | 사진 | 글 |
| --- | --- | --- | --- |
| 현행 | CanvusView | WritingView | RecordWritingView |
| 수정 | - | PhotoUploadView | WritingView |

- 이렇게 바꾸려고 하는데 회원님들의 의견은 어떤지 궁금합니다.

**Comment by sohnseoyeon** [comment]
좋아요! 저도 작업하면서 헷갈렸어서 더 직관적으로 파일명을 변경하는게 좋을 것 같습니다.

**Comment by HIBAR97** [comment]
그럼 캔버스 뷰가 Photo로 통합되는 방식인가요

**Comment by sohnseoyeon** [comment]
@HIBAR97 아뇨! 아마 캔버스 뷰는 그대로 간다는 말인 것 같아요

**Comment by HIBAR97** [comment]
아 확인확인

**Comment by oceanooooo** [comment]
찬성합니다.

**Comment by Damagucci-Juice** [comment]
진행 시킬게요 !
